# Generated by Django 4.2.7 on 2023-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(max_length=255, upload_to='transcribes/media')),
                ('srt_file', models.FileField(max_length=255, upload_to='transcribes/srt')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
