# Generated by Django 4.2.7 on 2023-11-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadlog',
            name='title',
            field=models.CharField(default='teste_title', max_length=255),
            preserve_default=False,
        ),
    ]
