# Generated by Django 4.2.7 on 2023-11-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber_app', '0002_fileuploadlog_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUploadLog',
            new_name='Videos',
        ),
    ]
